AM_CPPFLAGS = -I@top_srcdir@/include
noinst_LTLIBRARIES = libdolfin_la.la
libdolfin_la_la_SOURCES = \
			DefaultFactory.cpp\
			EpetraFactory.cpp\
			EpetraKrylovSolver.cpp\
			EpetraLUSolver.cpp\
			EpetraMatrix.cpp\
			EpetraPreconditioner.cpp\
			EpetraSparsityPattern.cpp\
			EpetraVector.cpp\
			JANPACKFactory.cpp\
			JANPACKKrylovSolver.cpp\
			JANPACKMat.cpp\
			JANPACKVec.cpp\
			LinearSolver.cpp\
			PETScFactory.cpp\
			PETScKrylovMatrix.cpp\
			PETScKrylovSolver.cpp\
			PETScLUSolver.cpp\
			PETScMatrix.cpp\
			PETScPreconditioner.cpp\
			PETScVector.cpp\
			SLEPcEigenvalueSolver.cpp\
			SingularSolver.cpp\
			SparsityPattern.cpp\
			solve.cpp

