include_HEADERS = dolfin.h

nobase_pkginclude_HEADERS = config/dolfin_config.h\
				elements/ElementLibrary.h\
				elements/ffc_L2proj_21.h\
				elements/ffc_L2proj_24.h\
				elements/ffc_L2proj_17.h\
				elements/ffc_07.h\
				elements/ffc_06.h\
				elements/ffc_02.h\
				elements/ffc_05.h\
				elements/ffc_14.h\
				elements/ffc_20.h\
				elements/ffc_L2proj_19.h\
				elements/ffc_L2proj_06.h\
				elements/ffc_L2proj_22.h\
				elements/ffc_19.h\
				elements/ffc_00.h\
				elements/ffc_L2proj_18.h\
				elements/ffc_L2proj_01.h\
				elements/ffc_21.h\
				elements/ffc_L2proj_11.h\
				elements/ffc_L2proj_13.h\
				elements/ffc_L2proj_00.h\
				elements/ffc_L2proj_23.h\
				elements/ffc_08.h\
				elements/ffc_L2proj_20.h\
				elements/ffc_L2proj_02.h\
				elements/ffc_L2proj_10.h\
				elements/ffc_24.h\
				elements/ffc_16.h\
				elements/ffc_L2proj_07.h\
				elements/ffc_22.h\
				elements/dolfin_elements.h\
				elements/ffc_03.h\
				elements/ffc_L2proj_04.h\
				elements/ProjectionLibrary.h\
				elements/ffc_04.h\
				elements/ffc_23.h\
				elements/ffc_11.h\
				elements/ffc_01.h\
				elements/ffc_10.h\
				elements/ffc_L2proj_08.h\
				elements/ffc_17.h\
				elements/ffc_L2proj_03.h\
				elements/ffc_L2proj_14.h\
				elements/ffc_L2proj_12.h\
				elements/ffc_15.h\
				elements/ffc_12.h\
				elements/ffc_18.h\
				elements/ffc_13.h\
				elements/ffc_L2proj_09.h\
				elements/ffc_L2proj_16.h\
				elements/ffc_L2proj_15.h\
				elements/ffc_L2proj_05.h\
				elements/ffc_09.h\
				io/XMLFiniteElement.h\
				io/Checkpoint.h\
				io/XMLMeshFunction.h\
				io/XMLFile.h\
				io/XMLGraph.h\
				io/XMLMatrix.h\
				io/PXMLMesh.h\
				io/File.h\
				io/XMLFunction.h\
				io/Encoder.h\
				io/MatlabFile.h\
				io/XYZFile.h\
				io/STLFile.h\
				io/XMLMesh.h\
				io/XMLVector.h\
				io/VTKFile.h\
				io/XMLParameterList.h\
				io/RAWFile.h\
				io/OctaveFile.h\
				io/base64.h\
				io/dolfin_io.h\
				io/BinaryFile.h\
				io/MFile.h\
				io/XMLDofMap.h\
				io/GenericFile.h\
				io/XMLObject.h\
				parameter/DefaultParameters.h\
				parameter/dolfin_parameter.h\
				parameter/Parametrized.h\
				parameter/parameters.h\
				parameter/ParameterSystem.h\
				parameter/Parameter.h\
				parameter/ParameterList.h\
				parameter/ParameterValue.h\
				function/GenericFunction.h\
				function/UFCFunction.h\
				function/SpecialFunctions.h\
				function/UserFunction.h\
				function/DiscreteFunction.h\
				function/dolfin_function.h\
				function/ConstantFunction.h\
				function/SubFunction.h\
				function/Function.h\
				main/dolfin_main.h\
				main/MPI.h\
				main/SubSystemsManager.h\
				main/dolfin_doc.h\
				main/init.h\
				math/Lagrange.h\
				math/Legendre.h\
				math/basic.h\
				math/dolfin_math.h\
				quadrature/GaussianQuadrature.h\
				quadrature/LobattoQuadrature.h\
				quadrature/GaussQuadrature.h\
				quadrature/RadauQuadrature.h\
				quadrature/Quadrature.h\
				quadrature/dolfin_quadrature.h\
				mesh/LocalMeshCoarsening.h\
				mesh/Edge.h\
				mesh/rounding.h\
				mesh/predicates_init.h\
				mesh/MeshOrdering.h\
				mesh/Rectangle.h\
				mesh/Cell.h\
				mesh/RivaraRefinement.h\
				mesh/Box.h\
				mesh/MeshDistributedData.h\
				mesh/MeshData.h\
				mesh/BoundaryMesh.h\
				mesh/Vertex.h\
				mesh/Mesh.h\
				mesh/MeshGeometry.h\
				mesh/MeshEntity.h\
				mesh/GeometricPredicates.h\
				mesh/MeshHierarchyAlgorithms.h\
				mesh/UnitSquare.h\
				mesh/MeshPartition.h\
				mesh/TopologyComputation.h\
				mesh/MeshRenumber.h\
				mesh/UniformMeshRefinement.h\
				mesh/TetrahedronCell.h\
				mesh/GlobalFacetMap.h\
				mesh/Face.h\
				mesh/Point.h\
				mesh/RefinementManager.h\
				mesh/BoundaryComputation.h\
				mesh/UnitCircle.h\
				mesh/UnitSphere.h\
				mesh/MeshTopology.h\
				mesh/MeshSmoothData.h\
				mesh/MeshSmoothing.h\
				mesh/UnitCube.h\
				mesh/dolfin_mesh.h\
				mesh/LoadBalancer.h\
				mesh/GTSInterface.h\
				mesh/MPIMeshCommunicator.h\
				mesh/UnitInterval.h\
				mesh/LocalMeshRefinement.h\
				mesh/DomainBoundary.h\
				mesh/MeshEditor.h\
				mesh/SubDomain.h\
				mesh/MeshConnectivity.h\
				mesh/MeshHierarchy.h\
				mesh/ALEType.h\
				mesh/ALE.h\
				mesh/PointCell.h\
				mesh/TriangleCell.h\
				mesh/MeshFunction.h\
				mesh/Facet.h\
				mesh/IntersectionDetector.h\
				mesh/IntervalCell.h\
				mesh/CellType.h\
				mesh/MeshEntityIterator.h\
				mesh/MeshFunctionConverter.h\
				la/AMGSolver.h\
				la/MultigridScheme.h\
				la/KrylovSolver.h\
				la/PreconditionerType.h\
				la/JANPACKKrylovSolver.h\
				la/JANPACKAMGSolver.h\
				la/PETScMatrix.h\
				la/GenericSparsityPattern.h\
				la/GenericVector.h\
				la/GenericTensor.h\
				la/JANPACKVec.h\
				la/NormalizationType.h\
				la/LUSolver.h\
				la/SparsityPattern.h\
				la/LinearAlgebraFactory.h\
				la/Vector.h\
				la/PETScLUSolver.h\
				la/JANPACKMat.h\
				la/JANPACKFactory.h\
				la/dolfin_la.h\
				la/DefaultFactory.h\
				la/PETScKrylovSolver.h\
				la/GenericMatrix.h\
				la/Matrix.h\
				la/solve.h\
				la/Scalar.h\
				la/SolverType.h\
				la/PETScPreconditioner.h\
				la/VectorNormType.h\
				la/PETScObject.h\
				la/PETScFactory.h\
				la/PETScKrylovMatrix.h\
				la/LinearSolver.h\
				la/PETScVector.h\
				la/SingularSolver.h\
				graph/GraphEditor.h\
				graph/DirectedClique.h\
				graph/dolfin_graph.h\
				graph/GraphPartition.h\
				graph/Graph.h\
				graph/UndirectedClique.h\
				fem/SubSystem.h\
				fem/UFC.h\
				fem/SparsityPatternBuilder.h\
				fem/DofMapSet.h\
				fem/assemble.h\
				fem/DirichletBC.h\
				fem/Form.h\
				fem/dolfin_fem.h\
				fem/Assembler.h\
				fem/PeriodicBC.h\
				fem/UFCCell.h\
				fem/DofMap.h\
				fem/BoundaryCondition.h\
				fem/UFCMesh.h\
				log/Event.h\
				log/Logger.h\
				log/dolfin_log.h\
				log/LogManager.h\
				log/Progress.h\
				log/LogStream.h\
				log/log.h\
				common/timing.h\
				common/types.h\
				common/Array.h\
				common/unittest.h\
				common/dolfin_common.h\
				common/constants.h\
				common/Variable.h\
				common/List.h\
				common/Timer.h



