include_HEADERS = dolfin.h

nobase_pkginclude_HEADERS = \
				adaptivity/dolfin_adaptivity.h\
				adaptivity/AdaptiveRefinement.h\
				adaptivity/SpaceTimeFunction.h\
				config/dolfin_config.h\
				common/assert.h\
				common/constants.h\
				common/dolfin_common.h\
				common/byteswap.h\
				common/system.h\
				common/timing.h\
				common/types.h\
				common/Array.h\
				common/AdjacentMapping.h\
				common/Check.h\
				common/Clonable.h\
				common/DistributedData.h\
				common/Distributed.h\
				common/Label.h\
				common/List.h\
				common/Test.h\
				common/Tokenized.h\
				common/Timer.h\
				common/Variable.h\
				elements/dolfin_elements.h\
				elements/ElementLibrary.h\
				evolution/dolfin_evolution.h\
				evolution/Time.h\
				evolution/TimeDependent.h\
				evolution/TimeSeries.h\
				evolution/TimeStepping.h\
				fem/dolfin_fem.h\
				fem/Assembler.h\
				fem/BilinearForm.h\
				fem/BoundaryCondition.h\
				fem/BoundaryNormal.h\
				fem/Coefficient.h\
				fem/CoefficientMap.h\
				fem/DirichletBC.h\
				fem/DofMap.h\
				fem/DofMapCache.h\
				fem/DofMapSet.h\
				fem/DofNumbering.h\
				fem/Equation.h\
				fem/FiniteElement.h\
				fem/FiniteElementSpace.h\
				fem/Form.h\
				fem/FormExpansion.h\
				fem/Functional.h\
				fem/FunctionSpaceMap.h\
				fem/LinearForm.h\
				fem/NodeNormal.h\
				fem/PeriodicBC.h\
				fem/PeriodicDofsMapping.h\
				fem/ScratchSpace.h\
				fem/SetOfBCs.h\
				fem/SlipBC.h\
				fem/SlipFrictionBC.h\
				fem/SparsityPatternBuilder.h\
				fem/SubSystem.h\
				fem/UFC.h\
				fem/UFCCell.h\
				fem/UFCCellIterator.h\
				fem/UFCCoefficient.h\
				fem/UFCExpression.h\
				fem/UFCHalo.h\
				fem/UFCMesh.h\
				fem/numbering/CG1s.h\
				fem/numbering/CG1v.h\
				fem/numbering/DG0s.h\
				fem/numbering/DG0v.h\
				fem/numbering/Parallel0.h\
				fem/numbering/Parallel1.h\
				fem/numbering/RealSpace.h\
				fem/numbering/Serial.h\
				function/dolfin_function.h\
				function/Analytic.h\
				function/Constant.h\
				function/Expression.h\
				function/Field.h\
				function/Function.h\
				function/FunctionDecomposition.h\
				function/FunctionInterpolation.h\
				function/GenericFunction.h\
				function/Real.h\
				function/SubFunction.h\
				function/UFCFunction.h\
				function/Value.h\
				function/ValueSpace.h\
				function/impl/CellCircumradius.h\
				function/impl/CellDiameter.h\
				function/impl/CellVolume.h\
				io/base64.h\
				io/dolfin_io.h\
				io/BinaryFile.h\
				io/Checkpoint.h\
				io/Encoder.h\
				io/File.h\
				io/GenericFile.h\
				io/OFFFile.h\
				io/STLFile.h\
				io/VTKFile.h\
				io/XMLFile.h\
				io/XMLMesh.h\
				io/XMLObject.h\
				la/dolfin_la.h\
				la/AMGSolver.h\
				la/DefaultFactory.h\
				la/GenericMatrix.h\
				la/GenericSparsityPattern.h\
				la/GenericTensor.h\
				la/GenericVector.h\
				la/JANPACKAMGSolver.h\
				la/JANPACKFactory.h\
				la/JANPACKKrylovSolver.h\
				la/JANPACKMat.h\
				la/JANPACKVec.h\
				la/KrylovSolver.h\
				la/LinearAlgebraFactory.h\
				la/LinearSolver.h\
				la/LAPACKMatrix.h\
				la/LAPACKVector.h\
				la/LUSolver.h\
				la/Matrix.h\
				la/MultigridScheme.h\
				la/NormalizationType.h\
				la/PETScFactory.h\
				la/PETScKrylovMatrix.h\
				la/PETScKrylovSolver.h\
				la/PETScLUSolver.h\
				la/PETScMatrix.h\
				la/PETScObject.h\
				la/PETScPreconditioner.h\
				la/PETScVector.h\
				la/PreconditionerType.h\
				la/Scalar.h\
				la/SolverType.h\
				la/SparsityPattern.h\
				la/Vector.h\
				la/VectorNormType.h\
				log/dolfin_log.h\
				log/Event.h\
				log/log.h\
				log/Logger.h\
				log/LogManager.h\
				log/LogStream.h\
				log/Progress.h\
				main/dolfin_doc.h\
				main/dolfin_main.h\
				main/init.h\
				main/MPI.h\
				main/Startup.h\
				main/SubSystemsManager.h\
				math/basic.h\
				math/dolfin_math.h\
				math/Chebyshev1.h\
				math/Chebyshev2.h\
				math/Jacobi.h\
				math/Lagrange.h\
				math/Legendre.h\
				math/LinearDistribution.h\
				math/PKDO.h\
				mesh/dolfin_mesh.h\
				mesh/algorithm.h \
				mesh/AffineMapping.h \
				mesh/ALE.h\
				mesh/BarycentricPoint.h\
				mesh/BoundaryMesh.h\
				mesh/BoundingBox.h\
				mesh/Box.h\
				mesh/Cell.h\
				mesh/CellType.h\
				mesh/CoarseningManager.h\
				mesh/DCell.h\
				mesh/DMesh.h\
				mesh/DomainBoundary.h\
				mesh/DVertex.h\
				mesh/Edge.h\
				mesh/EdgeKey.h\
				mesh/EntityKey.h\
				mesh/EquiAffineMapping.h \
				mesh/EuclideanBasis.h \
				mesh/Face.h\
				mesh/FaceKey.h\
				mesh/Facet.h\
				mesh/GeometricPredicates.h\
				mesh/GlobalFacetMap.h\
				mesh/GTSInterface.h\
				mesh/HexahedronCell.h\
				mesh/IntersectionDetector.h\
				mesh/IntervalCell.h\
				mesh/LoadBalancer.h\
				mesh/LocalMeshCoarsening.h\
				mesh/LocalMeshRefinement.h\
				mesh/Mapping.h \
				mesh/MappedManifold.h \
				mesh/Mesh.h\
				mesh/MeshDependent.h\
				mesh/MeshConnectivity.h\
				mesh/MeshDistributedData.h\
				mesh/MeshEditor.h\
				mesh/MeshEntity.h\
				mesh/MeshEntityIterator.h\
				mesh/MeshFunction.h\
				mesh/MeshGeometry.h\
				mesh/MetisInterface.h\
				mesh/ZoltanInterface.h\
				mesh/MeshPartition.h\
				mesh/MeshQuality.h\
				mesh/MeshQualityFunction.h\
				mesh/MeshRenumber.h\
				mesh/MeshSmoother.h\
				mesh/MeshSmoothData.h\
				mesh/MeshSmoothing.h\
				mesh/MeshTopology.h\
				mesh/MPIMeshCommunicator.h\
				mesh/PeriodicSubDomain.h\
				mesh/Point.h\
				mesh/PointCell.h\
				mesh/predicates_init.h\
				mesh/QuadrilateralCell.h\
				mesh/Rectangle.h\
				mesh/RefinementManager.h\
				mesh/RefinementPattern.h\
				mesh/RivaraRefinement.h\
				mesh/rounding.h\
				mesh/Space.h \
				mesh/SubDomain.h\
				mesh/StructuredGrid.h\
				mesh/TetrahedronCell.h\
				mesh/TriangleCell.h\
				mesh/UniformMeshRefinement.h\
				mesh/UnitCube.h\
				mesh/UnitDisk.h\
				mesh/UnitInterval.h\
				mesh/UnitSphere.h\
				mesh/UnitSquare.h\
				mesh/Vertex.h\
				mesh/VertexNormal.h\
				parameter/dolfin_parameter.h\
				parameter/DefaultParameters.h\
				parameter/Parameter.h\
				parameter/ParameterList.h\
				parameter/parameters.h\
				parameter/ParameterSystem.h\
				parameter/ParameterValue.h\
				parameter/Parametrized.h\
				quadrature/dolfin_quadrature.h\
				quadrature/GaussianQuadrature.h\
				quadrature/GaussQuadrature.h\
				quadrature/GaussQuadratureRule.h\
				quadrature/GaussTensorQuadratureRule.h\
				quadrature/LobattoQuadrature.h\
				quadrature/Quadrature.h\
				quadrature/QuadratureRule.h\
				quadrature/RadauQuadrature.h\
				quadrature/UFCCellIntegral.h\
				quadrature/UFCReferenceCell.h\
				ufl/dolfin_ufl.h\
				ufl/UFLarray.h\
				ufl/UFLdict.h\
				ufl/UFLrepr.h\
				ufl/UFL_tuple.h\
				ufl/UFLtype.h\
				ufl/UFLAlgebra.h\
				ufl/UFLArgument.h\
				ufl/UFLCell.h\
				ufl/UFLCellSurfaceArea.h\
				ufl/UFLCellVolume.h\
				ufl/UFLCircumradius.h\
				ufl/UFLClass.h\
				ufl/UFLCoefficient.h\
				ufl/UFLConditional.h\
				ufl/UFLData.h\
				ufl/UFLDifferentiation.h\
				ufl/UFLDomain.h\
				ufl/UFLElementList.h\
				ufl/UFLEnrichedElement.h\
				ufl/UFLEquation.h\
				ufl/UFLExpression.h\
				ufl/UFLFacetArea.h\
				ufl/UFLFacetNormal.h\
				ufl/UFLFamily.h\
				ufl/UFLFiniteElement.h\
				ufl/UFLFiniteElementSpace.h\
				ufl/UFLForm.h\
				ufl/UFLFormData.h\
				ufl/UFLGeometricQuantity.h\
				ufl/UFLIndex.h\
				ufl/UFLIndexed.h\
				ufl/UFLIndexSum.h\
				ufl/UFLIntegral.h\
				ufl/UFLList.h\
				ufl/UFLMixedElement.h\
				ufl/UFLObject.h\
				ufl/UFLQuadratureScheme.h\
				ufl/UFLRestrictedElement.h\
				ufl/UFLSpace.h\
				ufl/UFLSpatialCoordinate.h\
				ufl/UFLTensorElement.h\
				ufl/UFLTensors.h\
				ufl/UFLTuple.h\
				ufl/UFLValueArray.h\
				ufl/UFLVariable.h\
				ufl/UFLVectorElement.h

