AM_CPPFLAGS = -I@top_srcdir@/include
noinst_LTLIBRARIES = libdolfin_ode.la
libdolfin_ode_la_SOURCES = \
			Adaptivity.cpp\
			Alloc.cpp\
			ComplexODE.cpp\
			Controller.cpp\
			Dependencies.cpp\
			Dual.cpp\
			Homotopy.cpp\
			HomotopyJacobian.cpp\
			HomotopyODE.cpp\
			Method.cpp\
			MonoAdaptiveFixedPointSolver.cpp\
			MonoAdaptiveJacobian.cpp\
			MonoAdaptiveNewtonSolver.cpp\
			MonoAdaptiveTimeSlab.cpp\
			MonoAdaptivity.cpp\
			MultiAdaptiveFixedPointSolver.cpp\
			MultiAdaptiveJacobian.cpp\
			MultiAdaptiveNewtonSolver.cpp\
			MultiAdaptivePreconditioner.cpp\
			MultiAdaptiveTimeSlab.cpp\
			MultiAdaptivity.cpp\
			ODE.cpp\
			ODESolution.cpp\
			ODESolver.cpp\
			Partition.cpp\
			ReducedModel.cpp\
			Sample.cpp\
			TimeSlab.cpp\
			TimeSlabJacobian.cpp\
			TimeSlabSolver.cpp\
			TimeStepper.cpp\
			UpdatedMultiAdaptiveJacobian.cpp\
			cGqMethod.cpp\
			dGqMethod.cpp





