# This is an example of a simple SConstruct file for building
# programs against DOLFIN. To build this demo, just type 'scons'.

# -msse3 -msse3 -msse -ftree-vectorize -ftree-vectorizer-verbose=1

import os, commands

# Get compiler from pkg-config
compiler = commands.getoutput('pkg-config --variable=compiler dolfin')

# Create a SCons Environment based on the main os environment
env = Environment(ENV=os.environ, CXX="g++")

# Get compiler flags from pkg-config
env.ParseConfig('pkg-config --cflags --libs dolfin')

env.Append(CXXFLAGS='-DHAS_MTL')
#env.Append(CXXFLAGS='-DHAS_MTL -pg', LINKFLAGS='-pg')
#env.Append(CXXFLAGS='-DHAS_MTL -fopenmp',LINKFLAGS='-fopenmp')

# Program name
env.Program('demo', 'main.cpp')
