// Copyright (C) 2013 Aurélien Larcher.
// Licensed under the GNU LGPL Version 2.1.
//
// First added:  2014-02-03
// Last changed: 2014-02-03

#ifndef __DOLFIN_FINITE_ELEMENT_SPACE_H
#define __DOLFIN_FINITE_ELEMENT_SPACE_H

#include <dolfin/fem/DiscreteSpaces.h>
#include <dolfin/fem/FiniteElement.h>
#include <dolfin/mesh/Cell.h>

#include <ufc.h>

#include <string>

namespace dolfin
{

class DofMap;
class Form;
class Mesh;
class SubFunction;
class SubSystem;

/**
 *  DOCUMENTATION:
 *
 *  @class  FiniteElementSpace
 *
 *  @brief  Implements an abstraction for finite element spaces, defined on a
 *          mesh, for a given reference element and given a dofmap which is
 *          composed of the degrees of freedom generated by the transport of
 *          the reference element on each cell of the mesh.
 *          This class implements the UFL and FIAT interface, and the
 *          FiniteElement and DofMap member attributes conform with the
 *          specified UFC interface.
 *
 *  @author Aurélien Larcher <larcher@kth.se>
 */

class FiniteElementSpace
{

public:

  /// Create space from i-th coefficient space of given form
  FiniteElementSpace(Form& form, uint const i);

  /// Create space from i-th coefficient element of given form but on the mesh
  /// provided as argument
  FiniteElementSpace(Mesh& mesh, Form& form, uint const i);

  /// Create space from UFC finite element
  explicit FiniteElementSpace(Mesh& mesh, ufc::finite_element& element,
                              ufc::dofmap& dofmap, bool owner = false);

  /// Create space from UFL space definition for pre-generated elements
  explicit FiniteElementSpace(Mesh& mesh,
                              ufl::FiniteElementSpace const& element);

  /// Create a finite element space from ith subspace of given space
  FiniteElementSpace(FiniteElementSpace const& space, uint const i);

  /// Create a finite element space from given subspace
  FiniteElementSpace(FiniteElementSpace const& space, SubSystem const& sub);

  /// Create space similar to specified but on another mesh
  FiniteElementSpace(Mesh& other_mesh, FiniteElementSpace const& space);

  /// Copy constructor
  FiniteElementSpace(FiniteElementSpace const& other);

  /// Destructor
  ~FiniteElementSpace();

  /// Check if the finite element space definitions are identical
  bool operator ==(FiniteElementSpace const& other) const;
  bool operator !=(FiniteElementSpace const& other) const;

  /// Return mesh on which the discrete space is defined
  Mesh& mesh() const;

  /// Return cell on which the reference element is defined
  Cell& cell() const; //FIXME: Cannot const this due to Mesh implementation

  /// Return the element
  FiniteElement const& element() const;

  /// Return the dofmap
  DofMap const& dofmap() const;

  /// Returns a flattened representation of the space
  Array<FiniteElementSpace *> flatten() const;

  /// Display basic information
  void disp() const;

  //---------------------------------------------------------------------------

  /// Return whether the discrete space is defined per cell (discontinuous)
  bool is_cellwise_defined() const;

  /// Return whether the discrete space is piecewise constant
  bool is_cellwise_constant() const;

  /// Return whether the discrete space is defined at the vertices only
  bool is_vertex_based() const;

  /// Return whether the discrete space can be flattened to scalar elements
  bool is_flattenable() const;

  //--- UFL INTERFACE ---------------------------------------------------------

  /// Returns the family of the finite element
  /// UFL + FIAT
  ufl::Family::Type family() const;

  /// Returns the degree of the finite element
  /// UFL + FIAT
  uint degree() const;

  /// Return the metatype of the finite element
  /// UFL C++ only
  ufl::Family::Type metatype() const;

  /// Return UFL definition of the discrete space
  operator ufl::FiniteElementSpace const&() const
  {
    return *ufl_;
  }

private:

  Mesh& mesh_;
  mutable Cell cell_;
  FiniteElement const finite_element_;
  DofMap& dof_map_; // The dof map is owned by the DofMapCache instance.

  // UFL binding
  ufl::FiniteElementSpace const * const ufl_;

};

//-----------------------------------------------------------------------------
inline Mesh& FiniteElementSpace::mesh() const
{
  return mesh_;
}

//-----------------------------------------------------------------------------
inline ufl::Family::Type FiniteElementSpace::family() const
{
  return ufl_->family().type();
}

//-----------------------------------------------------------------------------
inline ufl::Family::Type FiniteElementSpace::metatype() const
{
  return ufl_->metatype();
}

//-----------------------------------------------------------------------------
inline uint FiniteElementSpace::degree() const
{
  return ufl_->degree();
}

}
/* namespace icorne */
#endif /* __DOLFIN_FINITE_ELEMENT_SPACE_H */
