// Copyright (C) 2013 Aurélien Larcher.
// Licensed under the GNU LGPL Version 2.1.

#ifndef __DOLFIN_FINITE_ELEMENT_SPACE_H
#define __DOLFIN_FINITE_ELEMENT_SPACE_H

#include <dolfin/fem/DiscreteSpaces.h>
#include <dolfin/fem/DofMap.h>
#include <dolfin/fem/FiniteElement.h>
#include <dolfin/mesh/Cell.h>
#include <dolfin/ufc/ufc.h>

#include <string>

namespace dolfin
{

class Form;
class Mesh;
class SubFunction;
class SubSystem;

/**
 *  DOCUMENTATION:
 *
 *  @class  FiniteElementSpace
 *
 *  @brief  Implements an abstraction for finite element spaces, defined on a
 *          mesh, for a given reference element and given a dofmap which is
 *          composed of the degrees of freedom generated by the transport of
 *          the reference element on each cell of the mesh.
 *          This class implements the UFL and FIAT interface, and the
 *          FiniteElement and DofMap member attributes conform with the
 *          specified UFC interface.
 *
 *  @author Aurélien Larcher <larcher@kth.se>
 */

class FiniteElementSpace
{

public:
  /// Create space from i-th coefficient space of given form
  FiniteElementSpace( Form & form, uint const i );

  /// Create space from i-th coefficient element of given form but on the mesh
  /// provided as argument
  FiniteElementSpace( Mesh & mesh, Form & form, uint const i );

  /// Create space from UFC finite element
  explicit FiniteElementSpace( Mesh &                      mesh,
                               ufc::finite_element const * element,
                               ufc::dofmap &               dofmap,
                               bool                        owner = false );

  /// Create a finite element space from ith subspace of given space
  FiniteElementSpace( FiniteElementSpace const & space, uint const i );

  /// Create a finite element space from given subspace
  FiniteElementSpace( FiniteElementSpace const & space, SubSystem const & sub );

  /// Create space similar to specified but on another mesh
  FiniteElementSpace( Mesh & other_mesh, FiniteElementSpace const & space );

  /// Copy constructor
  FiniteElementSpace( FiniteElementSpace const & other );

  /// Destructor
  ~FiniteElementSpace();

  /// Check if the finite element space definitions are identical
  bool operator==( FiniteElementSpace const & other ) const;
  bool operator!=( FiniteElementSpace const & other ) const;

  /// Return mesh on which the discrete space is defined
  Mesh & mesh() const;

  /// Return cell on which the reference element is defined
  Cell & cell() const; //!< @tod Cannot const this due to Mesh implementation

  /// Return the element
  FiniteElement const * element() const;

  /// Return the dofmap
  DofMap const & dofmap() const;

  /// Returns a flattened representation of the space
  Array< FiniteElementSpace * > flatten() const;

  /// Display basic information
  void disp() const;

  //---------------------------------------------------------------------------

  /// Return whether the discrete space is defined per cell (discontinuous)
  bool is_cellwise_defined() const;

  /// Return whether the discrete space is piecewise constant
  bool is_cellwise_constant() const;

  /// Return whether the discrete space is defined at the vertices only
  bool is_vertex_based() const;

  /// Return whether the discrete space can be flattened to scalar elements
  bool is_flattenable() const;

private:
  Mesh &                mesh_;
  mutable Cell          cell_;
  FiniteElement const * finite_element_;
  DofMap & dof_map_; // The dof map is owned by the DofMapCache instance.
};

//-----------------------------------------------------------------------------

inline Mesh & FiniteElementSpace::mesh() const
{
  return mesh_;
}

//-----------------------------------------------------------------------------

inline bool
  FiniteElementSpace::operator==( FiniteElementSpace const & other ) const
{
  return ( this->mesh() == other.mesh() )
         && ( this->element() == other.element() )
         && ( this->dofmap() == other.dofmap() );
}

//-----------------------------------------------------------------------------

inline bool
  FiniteElementSpace::operator!=( FiniteElementSpace const & other ) const
{
  return !( *this == other );
}

//-----------------------------------------------------------------------------

inline Cell & FiniteElementSpace::cell() const
{
  return cell_;
}

//-----------------------------------------------------------------------------

inline FiniteElement const * FiniteElementSpace::element() const
{
  return finite_element_;
}

//-----------------------------------------------------------------------------

inline DofMap const & FiniteElementSpace::dofmap() const
{
  return dof_map_;
}

//-----------------------------------------------------------------------------

inline bool FiniteElementSpace::is_cellwise_defined() const
{
  // FIXME num_entities should maybe be stored somewhere else
  std::vector< size_t > num_entities( finite_element_->topological_dimension(),
                                      0 );
  for ( uint d = 0; d <= finite_element_->topological_dimension(); ++d )
  {
    if ( mesh_.topology().connectivity( d ) )
    {
      num_entities[d] = mesh_.topology().global_size( d );
    }
  }

  return ( mesh_.num_global_cells() * dof_map_.num_element_support_dofs() )
         == dof_map_.global_dimension( num_entities );
}

//-----------------------------------------------------------------------------

inline bool FiniteElementSpace::is_cellwise_constant() const
{
  return is_cellwise_defined()
         && ( dof_map_.num_element_support_dofs() == finite_element_->value_size() );
}

//-----------------------------------------------------------------------------

inline bool FiniteElementSpace::is_vertex_based() const
{
  /// @todo Only a particular case.
  return     ( finite_element_->family() == Element::Family::CG )
         and ( finite_element_->degree() == 1 );
}

//-----------------------------------------------------------------------------

inline bool FiniteElementSpace::is_flattenable() const
{
  /// @todo Only a particular case.
  uint value_size = 1;
  for ( uint i = 0; i < finite_element_->value_rank(); ++i )
  {
    value_size *= finite_element_->value_dimension( i );
  }
  return ( finite_element_->flatten().size() == value_size );
}

//-----------------------------------------------------------------------------

} // end namespace dolfin

#endif /* __DOLFIN_FINITE_ELEMENT_SPACE_H */
