AM_CPPFLAGS = -I@top_srcdir@
noinst_LTLIBRARIES = libdolfin_fem.la
libdolfin_fem_la_SOURCES = \
			assemble.cpp\
			Assembler.cpp\
			BoundaryCondition.cpp\
			DirichletBC.cpp\
			DofMap.cpp\
			DofMapSet.cpp\
			Form.cpp\
			PeriodicBC.cpp\
			SparsityPatternBuilder.cpp\
			SubSystem.cpp\
			UFC.cpp
