AM_CPPFLAGS = -I@top_srcdir@/include
noinst_LTLIBRARIES = libdolfin_fem.la
libdolfin_fem_la_SOURCES = \
			Assembler.cpp\
			BilinearForm.cpp\
			BoundaryCondition.cpp\
			BoundaryNormal.cpp\
			Coefficient.cpp\
			CoefficientMap.cpp\
			DirichletBC.cpp\
			DofMap.cpp\
			DofMapCache.cpp\
			DofMapSet.cpp\
			DofNumbering.cpp\
			Equation.cpp\
			FiniteElement.cpp\
			FiniteElementSpace.cpp\
			FunctionSpaceMap.cpp\
			Form.cpp\
			Functional.cpp\
			LinearForm.cpp\
			NodeNormal.cpp\
			PeriodicBC.cpp\
			PeriodicDofsMapping.cpp\
			ScratchSpace.cpp\
			SlipBC.cpp\
			SlipFrictionBC.cpp\
			SparsityPatternBuilder.cpp\
			SubSystem.cpp\
			UFC.cpp \
			UFCHalo.cpp
