// Copyright (C) 2015 Aurélien Larcher.
// Licensed under the GNU LGPL Version 2.1.
//
// First added:  2015-04-24
// Last changed: 2015-04-24

#include <dolfin/fem/PeriodicDofsMapping.h>

#include <dolfin/common/constants.h>
#include <dolfin/fem/DofMap.h>
#include <dolfin/fem/UFCCell.h>
#include <dolfin/main/MPI.h>
#include <dolfin/mesh/BoundaryMesh.h>
#include <dolfin/mesh/Cell.h>
#include <dolfin/mesh/Facet.h>
#include <dolfin/mesh/IntersectionDetector.h>
#include <dolfin/mesh/MappedManifold.h>
#include <dolfin/mesh/Mesh.h>
#include <dolfin/mesh/PeriodicSubDomain.h>
#include <dolfin/mesh/Vertex.h>
#include <dolfin/mesh/Point.h>

#include <algorithm>
#include <cstring>
#include <iomanip>
#include <fstream>

namespace dolfin
{

//-----------------------------------------------------------------------------
bool onEntity(Point& p, MeshEntity& entity)
{
  // Check if the coordinates are on the same line as the line segment
  if ( entity.dim() == 1 )
  {
    // Create points
    Point v0 = Vertex(entity.mesh(), entity.entities(0)[0]).point();
    Point v1 = Vertex(entity.mesh(), entity.entities(0)[1]).point();

    // Create vectors
    Point v01 = v1 - v0;
    Point vp0 = v0 - p;
    Point vp1 = v1 - p;

    // Check if the length of the sum of the two line segments vp0 and vp1 is
    // equal to the total length of the entity
    if ( std::abs(v01.norm() - vp0.norm() - vp1.norm()) < DOLFIN_EPS )
    {
      return true;
    }
    else
    {
      return false;
    }
  }
  // Check if the coordinates are in the same plane as the triangular entity
  else if ( entity.dim() == 2 )
  {
    // Create points
    Point v0 = Vertex(entity.mesh(), entity.entities(0)[0]).point();
    Point v1 = Vertex(entity.mesh(), entity.entities(0)[1]).point();
    Point v2 = Vertex(entity.mesh(), entity.entities(0)[2]).point();

    // Create vectors
    Point v01 = v1 - v0;
    Point v02 = v2 - v0;
    Point vp0 = v0 - p;
    Point vp1 = v1 - p;
    Point vp2 = v2 - p;

    // Check if the sum of the area of the sub triangles is equal to the total
    // area of the entity
    if ( std::abs(v01.cross(v02).norm() - vp0.cross(vp1).norm() - vp1.cross(vp2).norm()
        - vp2.cross(vp0).norm()) < DOLFIN_EPS )
    {
      return true;
    }
    else
    {
      return false;
    }
  }

  error("On entity check is not implemented for given dimension).");

  return false;
}

//-----------------------------------------------------------------------------
PeriodicDofsMapping::PeriodicDofsMapping(DofMap const& dofmap) :
    dofmap_(dofmap),
    max_local_dimension_(0),
    Gindices_(NULL),
    Gxcoords_(NULL),
    Hcount_(NULL),
    Hoffsets_(NULL),
    Hindices_(NULL),
    Hxcoords_(NULL)
{
  init(dofmap);
}

//-----------------------------------------------------------------------------
PeriodicDofsMapping::~PeriodicDofsMapping()
{
}

//-----------------------------------------------------------------------------
void PeriodicDofsMapping::init(DofMap const& dofmap)
{
  if (!dofmap.mesh().has_periodic_constraint())
  {
    error("Mesh has no periodic constraint");
  }

  clear();

  //--- Create manifold generated by F^-1(H) --------------------------------
  Mesh& mesh = dofmap.mesh();
  uint const tdim = mesh.topology_dimension();
  uint const gdim = mesh.geometry_dimension();
  uint const maxgdim = Space::MAX_DIMENSION;
  Cell c0(mesh, 0);
  mesh.init(tdim, mesh.type().facet_dim());
  mesh.init(mesh.type().facet_dim(), tdim);

  // Collect facets with one vertex inside the subdomain
  BoundaryMesh& boundary = mesh.exterior_boundary();

  Array<MappedManifold *> const& manifold_list = mesh.periodic_mappings();
  uint totalcardGnI = 0;
  for (Array<MappedManifold *>::const_iterator it = manifold_list.begin();
      it != manifold_list.end(); ++it)
  {
   MappedManifold& manifold = *(*it);
   _set<uint> const& setG = manifold.Gfacets();
   _set<uint> const& setI = manifold.Ifacets();
   totalcardGnI += setG.size() - setI.size();
  }

  //--- Setup data structures -----------------------------------------------
  std::map<uint, uint> Gdofs_map;
  uint const num_facet_dofs = dofmap.num_facet_dofs();
  uint const max_numGdofs = num_facet_dofs * totalcardGnI;
  uint Gcount = 0;
  uint Hcount = 0;
  //dolfin_assert(max_numGdofs > 0);
  uint * Gdofs_indices = NULL;
  real * Gdofs_xcoords = NULL;
  Array<uint> * Hdofs_indices = NULL;
  Array<real> * Hdofs_xcoords = NULL;
  // Avoid allocating zero size array
  if(max_numGdofs > 0)
  {
    Gdofs_indices = new uint[max_numGdofs];
    Gdofs_xcoords = new real[max_numGdofs * gdim];
    Hdofs_indices = new Array<uint> [max_numGdofs];
    Hdofs_xcoords = new Array<real> [max_numGdofs];
  }

  // UFC dofmap data structures
  UFCCell ufc_cell0(c0);
  UFCCell ufc_cell1(c0);
  uint const local_dimension = dofmap.local_dimension();
  uint * dofsG = new uint[local_dimension];
  uint * dofsH = new uint[local_dimension];
  real ** coordinatesG = new real*[local_dimension];
  real ** coordinatesH = new real*[local_dimension];
  for (uint i = 0; i < local_dimension; ++i)
  {
    // Using same storage size as a Point
    coordinatesG[i] = new real[maxgdim];
    coordinatesH[i] = new real[maxgdim];
    std::memset(&coordinatesG[i][0], 0, maxgdim * sizeof(real));
    std::memset(&coordinatesH[i][0], 0, maxgdim * sizeof(real));
  }
  uint * facet_dofsG = new uint[num_facet_dofs];
  uint * facet_dofsH = new uint[num_facet_dofs];

  for (Array<MappedManifold *>::const_iterator it = manifold_list.begin();
       it != manifold_list.end(); ++it)
  {
    MappedManifold& manifold = *(*it);
    PeriodicSubDomain const& mapped = manifold.subdomain();
    _set<uint> const& setG = manifold.Gfacets();
    _set<uint> const& setH = manifold.Hfacets();
    _set<uint> const& setI = manifold.Ifacets();
    uint const GpmOffset = Gcount;

    //--- Collect dofs and exchange -------------------------------------------
    // Reserve array for mapped coordinates
    Point xG;

    //--- Exclude dofs located in I
    for (_set<uint>::const_iterator it = setI.begin(); it != setI.end(); ++it)
    {
      Facet facet(mesh, *it);
      Cell cell(mesh, facet.entities(tdim)[0]);
      uint facet_posI = cell.index(facet);
      ufc_cell0.update(cell);
      dofmap.tabulate_dofs(dofsG, ufc_cell0);
      dofmap.tabulate_facet_dofs(facet_dofsG, facet_posI);
      dofmap.tabulate_coordinates(coordinatesG, ufc_cell0);

      for (uint ii = 0; ii < num_facet_dofs; ++ii)
      {
        uint dofG = dofsG[facet_dofsG[ii]];
        real const * x = coordinatesG[facet_dofsG[ii]];
        // Determine if the dof is in I
        mapped.map(x, &xG[0]);
        if (mapped.inside(&xG[0], true) && mapped.inside(x, true))
        {
          Idofs_.insert(dofG);
        }
      }
    }

    //--- Collect dofs located in G to initialize data structure
    for (_set<uint>::const_iterator it = setG.begin(); it != setG.end(); ++it)
    {
      Facet facet(mesh, *it);
      Cell cell(mesh, facet.entities(tdim)[0]);
      uint facet_posG = cell.index(facet);
      ufc_cell0.update(cell);
      dofmap.tabulate_dofs(dofsG, ufc_cell0);
      dofmap.tabulate_facet_dofs(facet_dofsG, facet_posG);
      dofmap.tabulate_coordinates(coordinatesG, ufc_cell0);

      for (uint ii = 0; ii < num_facet_dofs; ++ii)
      {
        uint dofG = dofsG[facet_dofsG[ii]];
        real const * xG = coordinatesG[facet_dofsG[ii]];

        // Determine if the dof is in G (dofs in I are excluded)
        if (mapped.inside(xG, true))// && (Idofs_.count(dofG) == 0))
        {
          if(Gdofs_map.count(dofG) == 0 && !dofmap.is_ghost(dofG))
          {
            Gdofs_map[dofG] = Gcount;
            Gdofs_indices[Gcount] = dofG;
            std::copy(xG, xG + gdim, &Gdofs_xcoords[Gcount*gdim]);
            ++Gcount;
          }
        }
      }
    }

    for (std::map<uint, uint>::const_iterator it = Gdofs_map.begin();
        it != Gdofs_map.end(); ++it)
    {
      if (it->first != Gdofs_indices[it->second])
      {
        error("Corrupted G dofs mapping");
      }
    }

    //--- Collect dofs located in H and find corresponding local G facet
    for (_set<uint>::const_iterator it = setH.begin(); it != setH.end(); ++it)
    {
      Facet facetH(mesh, *it);
      Cell cellH(mesh, facetH.entities(tdim)[0]);
      uint facet_posH = cellH.index(facetH);
      ufc_cell1.update(cellH);
      dofmap.tabulate_dofs(dofsH, ufc_cell1);
      dofmap.tabulate_facet_dofs(facet_dofsH, facet_posH);
      dofmap.tabulate_coordinates(coordinatesH, ufc_cell1);

      for (uint ii = 0; ii < num_facet_dofs; ++ii)
      {
        uint dofH = dofsH[facet_dofsH[ii]];
        real const * xH = coordinatesH[facet_dofsH[ii]];

        // In case the subdomain is not well implemented
        std::copy(xH, xH + gdim, &xG[0]);
        // Find if H facet dof has a local corresponding local G dof
        mapped.map(xH, &xG[0]);
        if (mapped.inside(&xG[0], true) && (Hdofs_.count(dofH) == 0)
            && (Idofs_.count(dofH) == 0))
        {
          Array<uint> matching_facets;
          boundary.intersector().overlap(xG, matching_facets);
          if(!matching_facets.empty())
          {
            Hdofs_.insert(dofH);
            //message("dofH %8d : %1d facets", dofH, matching_facets.size() );
            for (Array<uint>::iterator it = matching_facets.begin();
                 it != matching_facets.end(); ++it)
            {
              Cell cbG(boundary, *it);
              //FIXME: Bug in intersect functions.
              //if(!onEntity(xG, cbG))
              //{
              //  warning("Matching facet does not contain point");
              //  continue;
              //}
              Facet facetG(mesh, boundary.facet_index(cbG));
              Cell cellG(mesh, facetG.entities(tdim)[0]);
              uint facet_posG = cellG.index(facetG);
              ufc_cell0.update(cellG);
              dofmap.tabulate_dofs(dofsG, ufc_cell0);
              dofmap.tabulate_facet_dofs(facet_dofsG, facet_posG);

              for (uint jj = 0; jj < num_facet_dofs; ++jj)
              {
                // Find if the mapped dof is a valid G dof
                uint dofG = dofsG[facet_dofsG[jj]];
                std::map<uint, uint>::const_iterator itG = Gdofs_map.find(dofG);
                if(itG == Gdofs_map.end())
                {
                  continue;
                }
                uint iiG = itG->second;
                dolfin_assert(dofG == Gdofs_indices[iiG]);
                bool insert = true;
                Array<uint> const& Hidx = Hdofs_indices[iiG];
                for(Array<uint>::const_iterator it = Hidx.begin();
                it != Hidx.end(); ++it)
                {
                  if(*it == dofH)
                  {
                    insert = false;
                    break;
                  }
                }
                if(insert)
                {
                  ++Hcount;
                  Hdofs_indices[iiG].push_back(dofH);
                  for(uint d = 0; d < gdim; ++d)
                  {
                    Hdofs_xcoords[iiG].push_back(xH[d]);
                  }
                }
              }
            }
          }
        }
      }
    }

    if (mesh.is_distributed())
    {
#if HAVE_MPI
      //--- Exchange data -----------------------------------------------------
      uint rank = dolfin::MPI::rank();
      uint pe_size = dolfin::MPI::size();
      MPI_Status status;
      uint src = 0;
      uint dst = 0;
      int u_count = 0;
      int u_recvdata_size = Gcount - GpmOffset;
      int u_recvdata_maxi = 0;
      MPI_Allreduce(&u_recvdata_size, &u_recvdata_maxi, 1, MPI_INT, MPI_MAX,
                    dolfin::MPI::DOLFIN_COMM);
      uint * u_recvbuff = new uint[u_recvdata_maxi];
      Array<uint> u_sendbuff;
      int r_recvdata_size = u_recvdata_size * gdim;
      int r_recvdata_maxi = u_recvdata_maxi * gdim;
      real * r_recvbuff = new real[r_recvdata_maxi];
      Array<real> r_sendbuff;

      uint * u_offsets = new uint[pe_size];
      uint * r_offsets = new uint[pe_size];
      uint * u_datsize = new uint[pe_size];
      uint * r_datsize = new uint[pe_size];
      for (int j = 1; j < (int) pe_size; ++j)
      {
        src = (rank - j + pe_size) % pe_size;
        dst = (rank + j) % pe_size;

        MPI_Sendrecv(&Gdofs_indices[GpmOffset], u_recvdata_size, MPI_UNSIGNED,
                     dst, 1, &u_recvbuff[0], u_recvdata_maxi, MPI_UNSIGNED, src,
                     1, dolfin::MPI::DOLFIN_COMM, &status);

        MPI_Get_count(&status, MPI_UNSIGNED, &u_count);

        MPI_Sendrecv(&Gdofs_xcoords[GpmOffset * gdim], r_recvdata_size,
                     MPI_DOUBLE, dst, 1, &r_recvbuff[0], r_recvdata_maxi,
                     MPI_DOUBLE, src, 1, dolfin::MPI::DOLFIN_COMM, &status);

        // If the local mesh contains H facets find matching G facets
        u_offsets[src] = u_sendbuff.size();
        r_offsets[src] = r_sendbuff.size();
        if (manifold.num_cells() > 0)
        {
          for (uint ii = 0; ii < (uint) u_count; ++ii)
          {
            uint const dofG = u_recvbuff[ii];
            std::copy(&r_recvbuff[ii * gdim], &r_recvbuff[ii * gdim] + gdim,
                      &xG[0]);

            Array<uint> matching_facets;
            manifold.intersector().overlap(xG, matching_facets);
            if (!matching_facets.empty())
            {
              u_sendbuff.push_back(dofG);
              u_sendbuff.push_back(0); // Reserve matching dofs

              _set<uint> matching;
              for (Array<uint>::iterator it = matching_facets.begin();
                   it != matching_facets.end(); ++it)
              {
                Cell cm(manifold, *it);
                //FIXME: Bug in intersect functions.
                //if(!onEntity(xG, cm))
                //{
                //  warning("Matching facet does not contain point");
                //  continue;
                //}
                Facet facet(mesh, manifold.facet_index(cm));
                Cell cell(mesh, facet.entities(tdim)[0]);
                uint facet_posH = cell.index(facet);
                ufc_cell1.update(cell);
                dofmap.tabulate_dofs(dofsH, ufc_cell1);
                dofmap.tabulate_facet_dofs(facet_dofsH, facet_posH);
                dofmap.tabulate_coordinates(coordinatesH, ufc_cell1);

                for (uint jj = 0; jj < num_facet_dofs; ++jj)
                {
                  uint dofH = dofsH[facet_dofsH[jj]];
                  real const * xH = coordinatesH[facet_dofsH[jj]];
                  std::copy(xH, xH + gdim, &xG[0]);
                  mapped.map(xH, &xG[0]);
                  if (mapped.inside(&xG[0], true)
                      && (matching.count(dofH) == 0))
                  {
                    matching.insert(dofH);
                    u_sendbuff.push_back(dofH);
                    for (uint d = 0; d < gdim; ++d)
                    {
                      r_sendbuff.push_back(xH[d]);
                    }
                  }
                }
              }
              dolfin_assert(*(u_sendbuff.rbegin() + matching.size()) == 0);
              *(u_sendbuff.rbegin() + matching.size()) = matching.size();
            }
          }
          //
        }
        u_datsize[src] = u_sendbuff.size() - u_offsets[src];
        r_datsize[src] = r_sendbuff.size() - r_offsets[src];
      }

      //
      u_recvdata_size = u_sendbuff.size();
      u_recvdata_maxi = 0;
      MPI_Allreduce(&u_recvdata_size, &u_recvdata_maxi, 1, MPI_INT, MPI_MAX,
                    dolfin::MPI::DOLFIN_COMM);
      delete[] u_recvbuff;
      u_recvbuff = NULL;
      u_recvbuff = new uint[u_recvdata_maxi];
      r_recvdata_size = r_sendbuff.size();
      r_recvdata_maxi = 0;
      MPI_Allreduce(&r_recvdata_size, &r_recvdata_maxi, 1, MPI_INT, MPI_MAX,
                    dolfin::MPI::DOLFIN_COMM);
      delete[] r_recvbuff;
      r_recvbuff = NULL;
      r_recvbuff = new real[r_recvdata_maxi];

      for (int j = 1; j < (int) pe_size; ++j)
      {
        src = (rank - j + pe_size) % pe_size;
        dst = (rank + j) % pe_size;

        MPI_Sendrecv(&u_sendbuff[u_offsets[dst]], u_datsize[dst], MPI_UNSIGNED,
                     dst, 1, &u_recvbuff[0], u_recvdata_maxi, MPI_UNSIGNED, src,
                     1, dolfin::MPI::DOLFIN_COMM, &status);

        MPI_Get_count(&status, MPI_UNSIGNED, &u_count);

        MPI_Sendrecv(&r_sendbuff[r_offsets[dst]], r_datsize[dst], MPI_DOUBLE,
                     dst, 1, &r_recvbuff[0], r_recvdata_maxi, MPI_DOUBLE, src,
                     1, dolfin::MPI::DOLFIN_COMM, &status);

        uint uii = 0;
        uint rii = 0;
        while (uii < (uint) u_count)
        {
          uint const dof = u_recvbuff[uii];
          ++uii;
          uint const nbH = u_recvbuff[uii];
          ++uii;
          std::map<uint, uint>::const_iterator itG = Gdofs_map.find(dof);
          if (itG == Gdofs_map.end())
          {
            error("No G dof %d sent from rank %d", dof, src);
          }
          Array<uint>& Hidx = Hdofs_indices[itG->second];
          Array<real>& Hxcs = Hdofs_xcoords[itG->second];
          _set<uint> existing(Hidx.begin(), Hidx.end());
          for (uint i = 0; i < nbH; ++i)
          {
            if (existing.count(u_recvbuff[uii]) == 0)
            {
              ++Hcount;
              Hidx.push_back(u_recvbuff[uii]);
              for (uint d = 0; d < gdim; ++d)
              {
                Hxcs.push_back(r_recvbuff[rii + d]);
              }
            }
            ++uii;
            rii += gdim;
          }
        }
      }
      delete[] u_datsize;
      delete[] r_datsize;
      delete[] u_offsets;
      delete[] r_offsets;
      delete[] u_recvbuff;
      delete[] r_recvbuff;
#endif
    }
  }

  // Finalize data structures
  dolfin_assert(Gcount == Gdofs_map.size());
  Gindices_ = new uint[Gcount];
  std::memset(Gindices_, 0, Gcount * sizeof(uint));
  Gxcoords_ = new real[Gcount * maxgdim];
  std::memset(Gxcoords_, 0, Gcount * maxgdim * sizeof(real));
  Hcount_ = new uint[Gcount];
  std::memset(Hcount_, 0, Gcount * sizeof(uint));
  Hoffsets_ = new uint[Gcount];
  std::memset(Hoffsets_, 0, Gcount * sizeof(uint));
  Hindices_ = new uint[Hcount];
  std::memset(Hindices_, 0, Hcount * sizeof(uint));
  Hxcoords_ = new real[Hcount * maxgdim];
  std::memset(Hxcoords_, 0, Hcount * maxgdim * sizeof(real));
  uint offset = 0;
  max_local_dimension_ = 0;
  for (uint ii = 0; ii < Gcount; ++ii)
  {
    uint const dof = Gdofs_indices[ii];
    uint const iG = Gdofs_map[dof];

    //
    Gindices_[ii] = Gdofs_indices[ii];
    std::copy(&Gdofs_indices[ii * gdim], &Gdofs_indices[ii * gdim] + gdim,
              &Gxcoords_[ii * maxgdim]);
    //
    Array<uint> const& Hidx = Hdofs_indices[iG];
    uint const num_Hdofs = Hidx.size();
    Hcount_[ii] = num_Hdofs;
    std::copy(&Hidx[0], &Hidx[0] + num_Hdofs, &Hindices_[offset]);
    Array<real> const& Hxcs = Hdofs_xcoords[iG];
    dolfin_assert(Hxcs.size() == gdim * Hidx.size());
    for (uint jj = 0; jj < num_Hdofs; ++jj)
    {
      std::copy(&Hxcs[jj * gdim], &Hxcs[jj * gdim] + gdim,
                &Hxcoords_[(offset + jj) * maxgdim]);
    }

    //
    Goffsets_[dof] = ii;
    Hoffsets_[ii] = offset;
    max_local_dimension_ = std::max(max_local_dimension_, num_Hdofs);
    offset += num_Hdofs;
  }
  //
  delete[] Hdofs_xcoords;
  delete[] Hdofs_indices;
  delete[] Gdofs_xcoords;
  delete[] Gdofs_indices;

  //
  delete[] facet_dofsH;
  delete[] facet_dofsG;
  for (uint i = 0; i < local_dimension; ++i)
  {
    delete[] coordinatesG[i];
    delete[] coordinatesH[i];
  }
  delete[] coordinatesG;
  delete[] coordinatesH;
  delete[] dofsH;
  delete[] dofsG;

}

//-----------------------------------------------------------------------------
void PeriodicDofsMapping::clear()
{
  max_local_dimension_ = 0;
  Goffsets_.clear();
  delete[] Gindices_;
  Gindices_ = NULL;
  delete[] Gxcoords_;
  Gxcoords_ = NULL;
  Hdofs_.clear();
  delete[] Hcount_;
  Hcount_ = NULL;
  delete[] Hoffsets_;
  Hoffsets_ = NULL;
  delete[] Hindices_;
  Hindices_ = NULL;
  delete[] Hxcoords_;
  Hxcoords_ = NULL;
  Idofs_.clear();
}

//-----------------------------------------------------------------------------
uint PeriodicDofsMapping::max_local_dimension() const
{
  return max_local_dimension_;
}

//-----------------------------------------------------------------------------
uint PeriodicDofsMapping::num_Gdofs() const
{
  return Goffsets_.size();
}

//-----------------------------------------------------------------------------
uint PeriodicDofsMapping::num_Hdofs() const
{
  return Hdofs_.size();
}

//-----------------------------------------------------------------------------
uint PeriodicDofsMapping::num_Idofs() const
{
  return Idofs_.size();
}

//-----------------------------------------------------------------------------
bool PeriodicDofsMapping::is_Gdof(uint i) const
{
  return (Goffsets_.find(i) != Goffsets_.end());
}

//-----------------------------------------------------------------------------
bool PeriodicDofsMapping::is_Hdof(uint i) const
{
  return (Hdofs_.count(i) > 0);
}

//-----------------------------------------------------------------------------
bool PeriodicDofsMapping::is_Idof(uint i) const
{
  return (Idofs_.count(i) > 0);
}

//-----------------------------------------------------------------------------
uint const * PeriodicDofsMapping::get_Gindices() const
{
  return Gindices_;
}

//-----------------------------------------------------------------------------
void PeriodicDofsMapping::tabulate_dofs(uint Gdof, uint * Hdofs,
                                        uint& count) const
{
  OffsetMap::const_iterator it = Goffsets_.find(Gdof);
  if (it == Goffsets_.end())
  {
    error("Requested dof is not periodic");
  }
  else
  {
    count = Hcount_[it->second];
    std::memcpy(&Hdofs[0], &Hindices_[Hoffsets_[it->second]],
                count * sizeof(uint));
  }
}

//-----------------------------------------------------------------------------
void PeriodicDofsMapping::tabulate_dofs(uint i, uint * Gdof, uint * Hdofs,
                                        uint& count) const
{
  dolfin_assert(i < Goffsets_.size());
  count = Hcount_[i];
  *Gdof = Gindices_[i];
  std::memcpy(&Hdofs[0], &Hindices_[Hoffsets_[i]], count * sizeof(uint));
}

//-----------------------------------------------------------------------------
void PeriodicDofsMapping::tabulate_coordinates(uint Gdof, real * Gcoords,
                                               real ** Hcoords, uint& count) const
{
  OffsetMap::const_iterator it = Goffsets_.find(Gdof);
  if (it == Goffsets_.end())
  {
    error("Requested dof is not periodic");
  }
  else
  {
    std::memcpy(&Gcoords[0],
                &Gxcoords_[it->second * Space::MAX_DIMENSION],
                Space::MAX_DIMENSION * sizeof(real));
    count = Hcount_[it->second];
    for (uint dof = 0; dof < count; ++dof)
    {
      std::memcpy(
          &Hcoords[dof][0],
          &Hxcoords_[Hoffsets_[it->second] + dof * Space::MAX_DIMENSION],
          Space::MAX_DIMENSION * sizeof(real));
    }
  }
}

//-----------------------------------------------------------------------------
void PeriodicDofsMapping::tabulate_coordinates(uint i, uint * Gdof,
                                               real * Gcoords, real ** Hcoords,
                                               uint& count) const
{
  dolfin_assert(i < Goffsets_.size());
  count = Hcount_[i];
  *Gdof = Gindices_[i];
  std::memcpy(&Gcoords[0],
              &Gxcoords_[i * Space::MAX_DIMENSION],
              Space::MAX_DIMENSION * sizeof(real));
  for (uint dof = 0; dof < count; ++dof)
  {
    std::memcpy(&Hcoords[dof][0],
                &Hxcoords_[Hoffsets_[i] + dof * Space::MAX_DIMENSION],
                Space::MAX_DIMENSION * sizeof(real));
  }
}

//-----------------------------------------------------------------------------
void PeriodicDofsMapping::disp() const
{
  section("PeriodicDofsMapping");
  prm("Max local dimension" , max_local_dimension_);
  prm("Number of G dofs"    , Goffsets_.size());
  end();
  //
  uint maxgdim = Space::MAX_DIMENSION;
  for (OffsetMap::const_iterator it = Goffsets_.begin(); it != Goffsets_.end();
       ++it)
  {
    uint dof = it->first;
    uint iid = it->second;
    std::stringstream ss;
    if (dofmap_.is_ghost(dof))
    {
      ss << std::setw(2) << "g";
    }
    else
    {
      ss << std::setw(2) << " ";
    }
    ss << std::setw(6) << dof << " : ";

    uint off = Hoffsets_[iid];
    uint const * Hidx = &Hindices_[off];
    real const * Hxcs = &Hxcoords_[off * maxgdim];

    for (uint i = 0; i < Hcount_[iid]; ++i)
    {
      ss << " " << std::setw(6) << Hidx[i] << " (";
      for (uint d = 0; d < maxgdim; ++d)
      {
        ss << " " << std::fixed << std::setw(8) << Hxcs[i * maxgdim + d];
      }
      ss << " ) ";
    }
    ss << std::setw(4) << Hcount_[iid];
    message("%s", ss.str().c_str());
  }

  end();
}

//-----------------------------------------------------------------------------

}
