AM_CPPFLAGS = -I@top_srcdir@/include
noinst_LTLIBRARIES = libdolfin_mesh.la
libdolfin_mesh_la_SOURCES = \
			AffineMapping.cpp\
			BoundaryMesh.cpp\
			Box.cpp\
			CellType.cpp\
			Connectivity.cpp\
			DMesh.cpp\
			EquiAffineMapping.cpp\
			EuclideanBasis.cpp\
			GeometricPredicates.cpp\
			GTSInterface.cpp\
			HexahedronCell.cpp\
			IntersectionDetector.cpp\
			IntervalCell.cpp\
			LoadBalancer.cpp\
			MappedManifold.cpp\
			Mesh.cpp\
			MeshDependent.cpp\
			MeshDistributedData.cpp\
			MeshEditor.cpp\
			MeshEntity.cpp\
			MeshEntityIterator.cpp\
			MeshGeometry.cpp\
			MeshOrdering.cpp\
			MeshPartition.cpp\
			MeshQuality.cpp\
			MeshQualityFunction.cpp\
			MeshRenumber.cpp\
			MeshSmoother.cpp\
			MeshSmoothing.cpp\
			MeshTopology.cpp\
			MetisInterface.cpp\
			MPIMeshCommunicator.cpp\
			PointCell.cpp\
			QuadrilateralCell.cpp\
			Rectangle.cpp\
			RefinementPattern.cpp\
			RivaraRefinement.cpp\
			StructuredGrid.cpp\
			SubDomain.cpp\
			TetrahedronCell.cpp\
			TriangleCell.cpp\
			UniformRefinement.cpp\
			UnitCube.cpp\
			UnitDisk.cpp\
			UnitInterval.cpp\
			UnitSphere.cpp\
			UnitSquare.cpp\
			VertexNormal.cpp\
			ZoltanInterface.cpp




