AM_CPPFLAGS = -I@top_srcdir@/include
noinst_LTLIBRARIES = libdolfin_mesh.la
libdolfin_mesh_la_SOURCES = \
			ALE.cpp\
			AffineMapping.cpp\
			BoundaryMesh.cpp\
			Box.cpp\
			Cell.cpp\
			CellType.cpp\
			CoarseningManager.cpp\
			DCell.cpp\
			DMesh.cpp\
			DVertex.cpp\
			Edge.cpp\
			EquiAffineMapping.cpp\
			Face.cpp\
			Facet.cpp\
			GTSInterface.cpp\
			GeometricPredicates.cpp\
			GlobalFacetMap.cpp\
			HexahedronCell.cpp\
			IntersectionDetector.cpp\
			IntervalCell.cpp\
			LoadBalancer.cpp\
			LocalMeshCoarsening.cpp\
			LocalMeshRefinement.cpp\
			MPIMeshCommunicator.cpp\
			MappedManifold.cpp\
			Mesh.cpp\
			MeshConnectivity.cpp\
			MeshData.cpp\
			MeshDependent.cpp\
			MeshDistributedData.cpp\
			MeshEditor.cpp\
			MeshEntity.cpp\
			MeshEntityIterator.cpp\
			MeshFunctionConverter.cpp\
			MeshGeometry.cpp\
			MeshHierarchy.cpp\
			MeshHierarchyAlgorithms.cpp\
			MeshQuality.cpp\
			MeshQualityFunction.cpp\
			MeshOrdering.cpp\
			MetisInterface.cpp\
			ZoltanInterface.cpp\
			MeshPartition.cpp\
			MeshRenumber.cpp\
			MeshSmoother.cpp\
			MeshSmoothData.cpp\
			MeshSmoothing.cpp\
			MeshTopology.cpp\
			Point.cpp\
			PointCell.cpp\
			QuadrilateralCell.cpp\
			Rectangle.cpp\
			RefinementManager.cpp\
			RivaraRefinement.cpp\
			StructuredGrid.cpp\
			SubDomain.cpp\
			TetrahedronCell.cpp\
			TopologyComputation.cpp\
			TriangleCell.cpp\
			UniformMeshRefinement.cpp\
			UnitCube.cpp\
			UnitDisk.cpp\
			UnitInterval.cpp\
			UnitSphere.cpp\
			UnitSquare.cpp\
			VertexNormal.cpp\
			Vertex.cpp




