AM_CPPFLAGS = -I@top_srcdir@/include
noinst_LTLIBRARIES = libdolfin_elements.la
libdolfin_elements_la_SOURCES = ffc_Brezzi_Douglas_Marini_1_2d.cpp\
				                        ffc_Discontinuous_Lagrange_0_1d.cpp\
				                        ffc_Discontinuous_Lagrange_0_2d.cpp\
				                        ffc_Discontinuous_Lagrange_0_2dVector.cpp\
				                        ffc_Discontinuous_Lagrange_0_3d.cpp\
				                        ffc_Discontinuous_Lagrange_0_3dVector.cpp\
				                        ffc_Discontinuous_Lagrange_1_1d.cpp\
				                        ffc_Discontinuous_Lagrange_1_2d.cpp\
				                        ffc_Discontinuous_Lagrange_1_2dVector.cpp\
				                        ffc_Discontinuous_Lagrange_1_3d.cpp\
				                        ffc_Discontinuous_Lagrange_1_3dVector.cpp\
				                        ffc_Discontinuous_Lagrange_2_1d.cpp\
				                        ffc_Discontinuous_Lagrange_2_2d.cpp\
				                        ffc_Discontinuous_Lagrange_2_2dVector.cpp\
				                        ffc_Discontinuous_Lagrange_2_3d.cpp\
				                        ffc_Discontinuous_Lagrange_2_3dVector.cpp\
				                        ffc_Lagrange_1_1d.cpp\
				                        ffc_Lagrange_1_2d.cpp\
				                        ffc_Lagrange_1_2dVector.cpp\
				                        ffc_Lagrange_1_3d.cpp\
				                        ffc_Lagrange_1_3dVector.cpp\
				                        ffc_Lagrange_2_1d.cpp\
				                        ffc_Lagrange_2_2d.cpp\
				                        ffc_Lagrange_2_2dVector.cpp\
				                        ffc_Lagrange_2_3d.cpp\
				                        ffc_Lagrange_2_3dVector.cpp

dist_data_DATA = element_library.inc elements.py generate_elements.py

EXTRA_DIST = ffc_Brezzi_Douglas_Marini_1_2d.h\
	           ffc_Discontinuous_Lagrange_0_1d.h\
	           ffc_Discontinuous_Lagrange_0_2d.h\
	           ffc_Discontinuous_Lagrange_0_2dVector.h\
	           ffc_Discontinuous_Lagrange_0_3d.h\
	           ffc_Discontinuous_Lagrange_0_3dVector.h\
	           ffc_Discontinuous_Lagrange_1_1d.h\
	           ffc_Discontinuous_Lagrange_1_2d.h\
	           ffc_Discontinuous_Lagrange_1_2dVector.h\
	           ffc_Discontinuous_Lagrange_1_3d.h\
	           ffc_Discontinuous_Lagrange_1_3dVector.h\
	           ffc_Discontinuous_Lagrange_2_1d.h\
	           ffc_Discontinuous_Lagrange_2_2d.h\
	           ffc_Discontinuous_Lagrange_2_2dVector.h\
	           ffc_Discontinuous_Lagrange_2_3d.h\
	           ffc_Discontinuous_Lagrange_2_3dVector.h\
	           ffc_Lagrange_1_1d.h\
	           ffc_Lagrange_1_2d.h\
	           ffc_Lagrange_1_2dVector.h\
	           ffc_Lagrange_1_3d.h\
	           ffc_Lagrange_1_3dVector.h\
	           ffc_Lagrange_2_1d.h\
	           ffc_Lagrange_2_2d.h\
	           ffc_Lagrange_2_2dVector.h\
	           ffc_Lagrange_2_3d.h\
	           ffc_Lagrange_2_3dVector.h
