SUBDIRS=

AM_CPPFLAGS = -I@top_srcdir@/include
noinst_LTLIBRARIES = libdolfin_la_petsc.la

libdolfin_la_petsc_la_SOURCES = PETScFactory.cpp\
			                          PETScKrylovMatrix.cpp\
			                          PETScKrylovSolver.cpp\
			                          PETScLUSolver.cpp\
			                          PETScMatrix.cpp\
			                          PETScPreconditioner.cpp\
			                          PETScVector.cpp
