SUBDIRS=

AM_CPPFLAGS = -I@top_srcdir@/include
noinst_LTLIBRARIES = libdolfin_mesh_celltypes.la

libdolfin_mesh_celltypes_la_SOURCES = CellType.cpp\
                                      HexahedronCell.cpp\
                                      IntervalCell.cpp\
                                      PointCell.cpp\
                                      QuadrilateralCell.cpp\
                                      TetrahedronCell.cpp\
                                      TriangleCell.cpp
