SUBDIRS=

AM_CPPFLAGS = -I@top_srcdir@/include
noinst_LTLIBRARIES = libdolfin_mesh_utilities.la

libdolfin_mesh_utilities_la_SOURCES = MeshOrdering.cpp\
                                      MeshPartition.cpp\
                                      MeshQuality.cpp\
                                      MeshRenumber.cpp\
                                      MeshSmoother.cpp\
                                      MeshSmoothing.cpp\
                                      MPIMeshCommunicator.cpp\
                                      RivaraRefinement.cpp\
                                      UniformRefinement.cpp
