AM_CPPFLAGS = -I@top_srcdir@/include
noinst_LTLIBRARIES = libdolfin_ufl.la
libdolfin_ufl_la_SOURCES = UFLarray.cpp\
                           UFLrepr.cpp\
                           UFLtuple.cpp\
                           UFLAlgebra.cpp\
                           UFLArgument.cpp\
                           UFLCell.cpp\
                           UFLCellSurfaceArea.cpp\
                           UFLCellVolume.cpp\
                           UFLCircumradius.cpp\
                           UFLClass.cpp\
                           UFLDifferentiation.cpp\
                           UFLDomain.cpp\
                           UFLElementList.cpp\
                           UFLEnrichedElement.cpp\
                           UFLExpression.cpp\
                           UFLFacetArea.cpp\
                           UFLFacetNormal.cpp\
                           UFLFamily.cpp\
                           UFLFiniteElement.cpp\
                           UFLFiniteElementBase.cpp\
                           UFLForm.cpp\
                           UFLGeometricQuantity.cpp\
                           UFLIndex.cpp\
                           UFLIndexed.cpp\
                           UFLIndexSum.cpp\
                           UFLIntegral.cpp\
                           UFLMixedElement.cpp\
                           UFLQuadratureScheme.cpp\
                           UFLRestrictedElement.cpp\
                           UFLSpace.cpp\
                           UFLSpatialCoordinate.cpp\
                           UFLTensorElement.cpp\
                           UFLTensors.cpp\
                           UFLVectorElement.cpp

dist_data_DATA =  
