AM_CPPFLAGS = -I@top_srcdir@/include
noinst_LTLIBRARIES = libdolfin_ufl.la
libdolfin_ufl_la_SOURCES = UFLCell.cpp\
                           UFLCellSurfaceArea.cpp\
                           UFLCellVolume.cpp\
                           UFLCircumradius.cpp\
                           UFLClass.cpp\
                           UFLDomain.cpp\
                           UFLElementList.cpp\
                           UFLEnrichedElement.cpp\
                           UFLFiniteElement.cpp\
                           UFLFiniteElementBase.cpp\
                           UFLGeometricQuantity.cpp\
                           UFLMixedElement.cpp\
                           UFLRestrictedElement.cpp\
                           UFLSpace.cpp\
                           UFLSpatialCoordinate.cpp\
                           UFLTensorElement.cpp\
                           UFLVectorElement.cpp

dist_data_DATA =  
