AM_CPPFLAGS = $(XML_CPPFLAGS) -I@top_srcdir@/include
noinst_LTLIBRARIES = libdolfin_io.la
libdolfin_io_la_SOURCES = \
			base64.cpp\
			BinaryFile.cpp\
			Checkpoint.cpp\
			File.cpp\
			GenericFile.cpp\
			OFFFile.cpp\
			VTKFile.cpp\
			XMLFile.cpp\
			XMLMesh.cpp\
			XMLObject.cpp\
			STLFile.cpp
