AM_CPPFLAGS = $(XML_CPPFLAGS) -I@top_srcdir@/include
noinst_LTLIBRARIES = libdolfin_io.la
libdolfin_io_la_SOURCES = \
			base64.cpp\
			BinaryFile.cpp\
			Checkpoint.cpp\
			File.cpp\
			GenericFile.cpp\
			MatlabFile.cpp\
			MFile.cpp\
			OctaveFile.cpp\
			PXMLMesh.cpp\
			RAWFile.cpp\
			VTKFile.cpp\
			XMLBLASFormData.cpp\
			XMLDofMap.cpp\
			XMLFile.cpp\
			XMLFiniteElement.cpp\
			XMLFunction.cpp\
			XMLGraph.cpp\
			XMLMatrix.cpp\
			XMLMesh.cpp\
			XMLMeshFunction.cpp\
			XMLObject.cpp\
			XMLParameterList.cpp\
			XMLVector.cpp\
			XYZFile.cpp
