check_PROGRAMS = exe
exe_SOURCES = test.cpp
exe_CPPFLAGS= -I@top_srcdir@/include @CHECK_CFLAGS@ $(CPPFLAGS)
exe_LDFLAGS = $(top_builddir)/src/.libs/libdolfin.a $(LDFLAGS) $(LIBS) @CHECK_LIBS@


EXTRA_DIST = Algebra/UFL_Algebra.h\
	     Argument/UFL_Argument.h\
	     Cell/UFL_Cell.h\
	     CellSurfaceArea/UFL_CellSurfaceArea.h\
             CellVolume/UFL_CellVolume.h\
             Circumradius/UFL_Circumradius.h\
             Class/UFL_Class.h\
             Coefficient/UFL_Coefficient.h\
             Conditional/UFL_Conditional.h\
             Differentiation/UFL_Differentitation.h\
             Domain/UFL_Domain.h\
             ElementList/UFL_ElementList.h\
             EnrichedElement/UFL_EnrichedElement.h\
             Equation/UFL_Equation.h\
             Expression/UFL_Expression.h\
             FacetArea/UFL_FacetArea.h\
             FacetNormal/UFL_FacetNormal.h\
             Family/UFL_Family.h\
             FiniteElement/UFL_FiniteElement.h\
	     FiniteElementBase/UFL_FiniteElementBase.h\
             Form/UFL_Form.h\
             GeometricQuantity/UFL_GeometricQuantitiy.h\
	     Index/UFL_Index.h\
             IndexSum/UFL_IndexSum.h\
	     Indexed/UFL_Indexed.h\
	     Integral/UFL_Integral.h\
	     List/UFL_List.h\
	     MixedElement/UFL_MixedElement.h\
	     Object/UFL_Object.h\
	     QuadratureScheme/UFL_QuadratureScheme.h\
	     RestrictedElement/UFL_RestrictedElement.h\
             Space/UFL_Space.h\
	     SpatialCoordinate/UFL_SpatialCoordinate.h\
	     TensorElement/UFL_TensorElement.h\
	     Tensors/UFL_Tensors.h\
	     Tuple/UFL_Tuple.h\
	     Variable/UFL_Variable.h\
	     VectorElement/UFL_VectorElement.h\
	     array/UFL_array.h\
	     repr/UFL_repr.h\
	     tuple/UFL_tuple.h\
	     type/UFL_type.h