LDFLAGS = $(XML_LDFLAGS)
SUBDIRS = common elements fem function graph io\
	la log main math mesh mf nls ode parameter\
	pde quadrature

include_HEADERS = dolfin.h

nobase_pkginclude_HEADERS = config/dolfin_config.h\
				elements/ElementLibrary.h\
				elements/ffc_L2proj_21.h\
				elements/ffc_L2proj_24.h\
				elements/ffc_L2proj_17.h\
				elements/ffc_07.h\
				elements/ffc_06.h\
				elements/ffc_02.h\
				elements/ffc_05.h\
				elements/ffc_14.h\
				elements/ffc_20.h\
				elements/ffc_L2proj_19.h\
				elements/ffc_L2proj_06.h\
				elements/ffc_L2proj_22.h\
				elements/ffc_19.h\
				elements/ffc_00.h\
				elements/ffc_L2proj_18.h\
				elements/ffc_L2proj_01.h\
				elements/ffc_21.h\
				elements/ffc_L2proj_11.h\
				elements/ffc_L2proj_13.h\
				elements/ffc_L2proj_00.h\
				elements/ffc_L2proj_23.h\
				elements/ffc_08.h\
				elements/ffc_L2proj_20.h\
				elements/ffc_L2proj_02.h\
				elements/ffc_L2proj_10.h\
				elements/ffc_24.h\
				elements/ffc_16.h\
				elements/ffc_L2proj_07.h\
				elements/ffc_22.h\
				elements/dolfin_elements.h\
				elements/ffc_03.h\
				elements/ffc_L2proj_04.h\
				elements/ProjectionLibrary.h\
				elements/ffc_04.h\
				elements/ffc_23.h\
				elements/ffc_11.h\
				elements/ffc_01.h\
				elements/ffc_10.h\
				elements/ffc_L2proj_08.h\
				elements/ffc_17.h\
				elements/ffc_L2proj_03.h\
				elements/ffc_L2proj_14.h\
				elements/ffc_L2proj_12.h\
				elements/ffc_15.h\
				elements/ffc_12.h\
				elements/ffc_18.h\
				elements/ffc_13.h\
				elements/ffc_L2proj_09.h\
				elements/ffc_L2proj_16.h\
				elements/ffc_L2proj_15.h\
				elements/ffc_L2proj_05.h\
				elements/ffc_09.h\
				nls/NonlinearProblem.h\
				nls/NewtonSolver.h\
				nls/dolfin_nls.h\
				io/XMLFiniteElement.h\
				io/Checkpoint.h\
				io/XMLMeshFunction.h\
				io/PVTKFile.h\
				io/XMLFile.h\
				io/XMLGraph.h\
				io/XMLMatrix.h\
				io/PXMLMesh.h\
				io/XMLBLASFormData.h\
				io/File.h\
				io/XMLFunction.h\
				io/Encoder.h\
				io/MatlabFile.h\
				io/XYZFile.h\
				io/XMLMesh.h\
				io/XMLVector.h\
				io/VTKFile.h\
				io/XMLParameterList.h\
				io/RAWFile.h\
				io/OctaveFile.h\
				io/base64.h\
				io/dolfin_io.h\
				io/BinaryFile.h\
				io/MFile.h\
				io/XMLDofMap.h\
				io/PythonFile.h\
				io/GenericFile.h\
				io/XMLObject.h\
				parameter/DefaultParameters.h\
				parameter/dolfin_parameter.h\
				parameter/Parametrized.h\
				parameter/parameters.h\
				parameter/ParameterSystem.h\
				parameter/Parameter.h\
				parameter/ParameterList.h\
				parameter/ParameterValue.h\
				function/GenericFunction.h\
				function/UFCFunction.h\
				function/SpecialFunctions.h\
				function/UserFunction.h\
				function/DiscreteFunction.h\
				function/dolfin_function.h\
				function/ConstantFunction.h\
				function/SubFunction.h\
				function/Function.h\
				function/ProjectL2.h\
				main/dolfin_main.h\
				main/MPI.h\
				main/SubSystemsManager.h\
				main/dolfin_doc.h\
				main/init.h\
				pde/NonlinearPDE.h\
				pde/dolfin_pde.h\
				pde/LinearPDE.h\
				ode/TimeSlabSolver.h\
				ode/MonoAdaptiveNewtonSolver.h\
				ode/dolfin_ode.h\
				ode/MultiAdaptiveTimeSlab.h\
				ode/HomotopyODE.h\
				ode/Dual.h\
				ode/MonoAdaptivity.h\
				ode/Partition.h\
				ode/Adaptivity.h\
				ode/MultiAdaptiveFixedPointSolver.h\
				ode/UpdatedMultiAdaptiveJacobian.h\
				ode/MonoAdaptiveTimeSlab.h\
				ode/ReducedModel.h\
				ode/ODESolver.h\
				ode/ODE.h\
				ode/dGqMethod.h\
				ode/ODESolution.h\
				ode/TimeSlabJacobian.h\
				ode/Alloc.h\
				ode/Sample.h\
				ode/Dependencies.h\
				ode/Method.h\
				ode/Homotopy.h\
				ode/HomotopyJacobian.h\
				ode/MultiAdaptivePreconditioner.h\
				ode/MultiAdaptiveNewtonSolver.h\
				ode/MultiAdaptivity.h\
				ode/Controller.h\
				ode/MonoAdaptiveFixedPointSolver.h\
				ode/cGqMethod.h\
				ode/ComplexODE.h\
				ode/TimeSlab.h\
				ode/MultiAdaptiveJacobian.h\
				ode/TimeStepper.h\
				ode/MonoAdaptiveJacobian.h\
				quadrature/GaussianQuadrature.h\
				quadrature/LobattoQuadrature.h\
				quadrature/GaussQuadrature.h\
				quadrature/RadauQuadrature.h\
				quadrature/Quadrature.h\
				quadrature/dolfin_quadrature.h\
				mesh/LocalMeshCoarsening.h\
				mesh/Edge.h\
				mesh/rounding.h\
				mesh/predicates_init.h\
				mesh/MeshOrdering.h\
				mesh/Rectangle.h\
				mesh/Cell.h\
				mesh/RivaraRefinement.h\
				mesh/Box.h\
				mesh/MeshDistributedData.h\
				mesh/MeshData.h\
				mesh/BoundaryMesh.h\
				mesh/Vertex.h\
				mesh/Mesh.h\
				mesh/MeshGeometry.h\
				mesh/MeshEntity.h\
				mesh/GeometricPredicates.h\
				mesh/MeshHierarchyAlgorithms.h\
				mesh/UnitSquare.h\
				mesh/MeshPartition.h\
				mesh/TopologyComputation.h\
				mesh/MeshRenumber.h\
				mesh/UniformMeshRefinement.h\
				mesh/TetrahedronCell.h\
				mesh/GlobalFacetMap.h\
				mesh/Face.h\
				mesh/Point.h\
				mesh/RefinementManager.h\
				mesh/BoundaryComputation.h\
				mesh/UnitCircle.h\
				mesh/UnitSphere.h\
				mesh/MeshTopology.h\
				mesh/MeshSmoothing.h\
				mesh/UnitCube.h\
				mesh/dolfin_mesh.h\
				mesh/LoadBalancer.h\
				mesh/GTSInterface.h\
				mesh/MPIMeshCommunicator.h\
				mesh/UnitInterval.h\
				mesh/LocalMeshRefinement.h\
				mesh/DomainBoundary.h\
				mesh/MeshEditor.h\
				mesh/SubDomain.h\
				mesh/MeshConnectivity.h\
				mesh/MeshHierarchy.h\
				mesh/ALEType.h\
				mesh/ALE.h\
				mesh/PointCell.h\
				mesh/TriangleCell.h\
				mesh/MeshFunction.h\
				mesh/Facet.h\
				mesh/IntersectionDetector.h\
				mesh/IntervalCell.h\
				mesh/CellType.h\
				mesh/MeshEntityIterator.h\
				math/Lagrange.h\
				math/Legendre.h\
				math/basic.h\
				math/dolfin_math.h\
				config.moved/dolfin_config.h\
				la/KrylovSolver.h\
				la/PreconditionerType.h\
				la/EpetraMatrix.h\
				la/JANPACKKrylovSolver.h\
				la/uBlasVector.h\
				la/PETScMatrix.h\
				la/GenericSparsityPattern.h\
				la/GenericVector.h\
				la/GenericTensor.h\
				la/JANPACKVec.h\
				la/NormalizationType.h\
				la/EpetraFactory.h\
				la/LUSolver.h\
				la/SparsityPattern.h\
				la/LinearAlgebraFactory.h\
				la/uBlasILUPreconditioner.h\
				la/uBlasPreconditioner.h\
				la/Vector.h\
				la/EpetraVector.h\
				la/EpetraSparsityPattern.h\
				la/uBlasLUSolver.h\
				la/PETScLUSolver.h\
				la/uBlasDummyPreconditioner.h\
				la/JANPACKMat.h\
				la/JANPACKFactory.h\
				la/dolfin_la.h\
				la/uBlasDenseMatrix.h\
				la/DefaultFactory.h\
				la/PETScKrylovSolver.h\
				la/GenericMatrix.h\
				la/Matrix.h\
				la/solve.h\
				la/Scalar.h\
				la/SolverType.h\
				la/PETScPreconditioner.h\
				la/SLEPcEigenvalueSolver.h\
				la/uBlasSparseMatrix.h\
				la/uBlasKrylovSolver.h\
				la/VectorNormType.h\
				la/PETScObject.h\
				la/PETScFactory.h\
				la/EpetraKrylovSolver.h\
				la/EpetraPreconditioner.h\
				la/uBlasKrylovMatrix.h\
				la/EpetraLUSolver.h\
				la/PETScKrylovMatrix.h\
				la/ublas.h\
				la/LinearSolver.h\
				la/uBlasFactory.h\
				la/PETScVector.h\
				la/SingularSolver.h\
				la/uBlasMatrix.h\
				graph/GraphEditor.h\
				graph/DirectedClique.h\
				graph/dolfin_graph.h\
				graph/GraphPartition.h\
				graph/Graph.h\
				graph/UndirectedClique.h\
				fem/SubSystem.h\
				fem/UFC.h\
				fem/SparsityPatternBuilder.h\
				fem/DofMapSet.h\
				fem/assemble.h\
				fem/DirichletBC.h\
				fem/Form.h\
				fem/dolfin_fem.h\
				fem/Assembler.h\
				fem/PeriodicBC.h\
				fem/UFCCell.h\
				fem/DofMap.h\
				fem/BoundaryCondition.h\
				fem/UFCMesh.h\
				mf/StiffnessMatrix.h\
				mf/MassMatrix.h\
				mf/dolfin_mf.h\
				mf/MatrixFactory.h\
				mf/ffc-forms/StiffnessMatrix2D.h\
				mf/ffc-forms/ConvectionMatrix3D.h\
				mf/ffc-forms/ConvectionMatrix2D.h\
				mf/ffc-forms/LoadVector2D.h\
				mf/ffc-forms/MassMatrix3D.h\
				mf/ffc-forms/LoadVector3D.h\
				mf/ffc-forms/MassMatrix2D.h\
				mf/ffc-forms/StiffnessMatrix3D.h\
				mf/ConvectionMatrix.h\
				mf/LoadVector.h\
				log/Event.h\
				log/Logger.h\
				log/dolfin_log.h\
				log/LogManager.h\
				log/Progress.h\
				log/LogStream.h\
				log/log.h\
				common/timing.h\
				common/types.h\
				common/Array.h\
				common/unittest.h\
				common/dolfin_common.h\
				common/TimeDependent.h\
				common/constants.h\
				common/Variable.h\
				common/List.h\
				common/Timer.h\
				common/simple_array.h

pkgconfigdir = $(libdir)/pkgconfig
pkgconfig_DATA = dolfin.pc

lib_LTLIBRARIES = libdolfin.la
libdolfin_la_SOURCES = 
libdolfin_la_LIBADD = \
		common/libdolfin_common.la\
		elements/libdolfin_elements.la\
		fem/libdolfin_fem.la\
		function/libdolfin_function.la\
		graph/libdolfin_graph.la\
		io/libdolfin_io.la\
		la/libdolfin_la.la\
		log/libdolfin_log.la\
		main/libdolfin_main.la\
		math/libdolfin_math.la\
		mesh/libdolfin_mesh.la\
		mf/libdolfin_mf.la\
		nls/libdolfin_nls.la\
		ode/libdolfin_ode.la\
		parameter/libdolfin_parameter.la\
		pde/libdolfin_pde.la\
		quadrature/libdolfin_quadrature.la


