AM_CPPFLAGS = -I@top_srcdir@/include
noinst_LTLIBRARIES = libdolfin_common.la
libdolfin_common_la_SOURCES = assert.cpp \
                              timing.cpp \
                              system.cpp \
                              AdjacentMapping.cpp \
                              DistributedData.cpp \
                              Test.cpp \
                              Variable.cpp
