SUBDIRS = convection-diffusion dg elasticity functional lift-drag mixed-poisson nonlinear-poisson periodic poisson poisson1D stokes
TESTS = convection-diffusion/demo\
	elasticity/demo\
	functional/demo\
	lift-drag/demo\
	mixed-poisson/demo\
	nonlinear-poisson/demo\
	periodic/demo\
	poisson/demo\
	poisson1D/demo
